name: EMAIL DECISION

on:
    workflow_dispatch:
        inputs:
            REGRESSION_TYPE:
                required: true
                type: choice
                description: what regression do you want to run?
                options:
                    - crm
                    - land
                    - tipp
                    - full-regression
            
            REGRESSION_ENVIRONMENT:
                required: true
                type: choice
                description: Which Salesforce environment do you want to run the regression against?
                options:
                    - test
                    - sit
                    - qa
                    - uat
                    - train
                    
            DELIVERABLE:
                required: true
                type: choice
                description: Which deliverable do you want to run the regression for?
                options:
                    - BU
                    - DEV
                default: BU

env:
    EMAIL_CRM: "kyle.nazzaro@nexteraenerty.com,earl.smith@nexteraenergy.com"
    EMAIL_LAND: "augusta.howells@nexteraenergy.com,lakshmi.thalla@nexteraenergy.com,harikrishna.chennur@nexteraenergy.com"
    EMAIL_TIPP: null
    EMAIL_DEV: "argenis.dominguez@nexteraenergy.com,ravi.bezawada@nexteraenergy.com,israel.felhandler@nexteraenergy.com"

jobs:
    print-correct-email-list:
        runs-on: ubuntu-latest

        steps:
            - name: Print Email List
              env:
                EMAIL_LIST: ${{ (inputs.DELIVERABLE == 'BU' && inputs.REGRESSION_TYPE == 'crm') && env.EMAIL_CRM || (inputs.DELIVERABLE == 'BU' && inputs.REGRESSION_TYPE == 'land') && env.EMAIL_LAND || (inputs.DELIVERABLE == 'BU' && inputs.REGRESSION_TYPE == 'tipp') && env.EMAIL_TIPP }}
            
              run: |
                echo ${{ env.EMAIL_LIST }}${{ (env.EMAIL_LIST != null) && ',' }}${{ env.EMAIL_DEV }}
