name: READ VARIABLES

on:
  push:
    branches:
      - main

env:
  SANDBOX_SECRETS: ${{ secrets.SANDBOX_SECRETS }}

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      SANDBOXES: ${{ steps.setup-sandboxes.outputs.SANDBOXES }}
    steps:
      - name: 🛸 Extract sandboxes
        id: extract-sandboxes
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const envJson = JSON.parse(process.env.SANDBOX_SECRETS);
            const sandboxes = Object.keys(envJson).map((str) => (`\"${str}\"`));
            console.log(sandboxes);
            return sandboxes;

      - name: ⚙️ setup sandboxes
        id: setup-sandboxes
        run: |
          echo "SANDBOXES=[${{ steps.extract-sandboxes.outputs.result }}]" >> $GITHUB_OUTPUT

  matrix:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sandbox: ${{ needs.setup-matrix.outputs.SANDBOXES }}

    steps:
      - name: 🚀 Set Password
        env:
          SANDBOX: ${{ matrix.sandbox }}
        uses: actions/github-script@v7
        id: set-password
        with:
          result-encoding: string
          script: |
            const envJson = JSON.parse(process.env.SANDBOX_SECRETS);
            const sandbox = process.env.SANDBOX
            return envJson[sandbox]
      
      - name: 🖨️ Print Password
        run: echo "${{steps.set-password.outputs.result}}"

          
