name: READ VARIABLES

on:
  push:
    branches:
      - main

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner: ['development', 'stage']

    steps:
      - name: Setup Node
        id: setup-noe
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v4

      - name: Print Required information
        id: print-information
        run: node .github/utils/index.js
          
