name: READ VARIABLES

on:
  push:
    branches:
      - main

env:
  SANDBOX_SECRETS: ${{ secrets.SANDBOX_SECRETS }}

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      SANDBOXES: ${{ steps.setup-sandboxes.outputs.SANDBOXES }}
    steps:
      - name: 🛸 Extract sandboxes
        id: extract-sandboxes
        uses: actions/github-script@v7
        with:
          script: |
            // JAVASCRIPT CODE
            const { SANDBOX_SECRETS } = process.env
            return Object.keys(JSON.parse(SANDBOX_SECRETS))

      - name: ⚙️ setup sandboxes
        id: setup-sandboxes
        run: |
          echo 'SANDBOXES=${{ steps.extract-sandboxes.outputs.result }}' >> $GITHUB_OUTPUT

  matrix:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sandbox: ${{ fromJson(needs.setup-matrix.outputs.SANDBOXES) }}

    steps:
      - name: 🚀 Set Password
        env:
          SANDBOX: ${{ matrix.sandbox }}

        uses: actions/github-script@v7
        id: set-password
        with:
          result-encoding: string
          script: |
            const envJson = JSON.parse(process.env.SANDBOX_SECRETS);
            const { SANDBOX } = process.env
            return envJson[SANDBOX]
      
      - name: 🖨️ Print Password
        run: echo "${{steps.set-password.outputs.result}}"

          
