name: READ VARIABLES

on:
  push:
    branches:
      - main

env:
  SANDBOX_SECRETS: ${{ secrets.SANDBOX_SECRETS }}

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner: ['stage', 'uat', 'qa']

    steps:
      - name: 🚀 Set Password
        env:
          SANDBOX: ${{ matrix.runner }}
        uses: actions/github-script@v6
        id: set-password
        with:
          result-encoding: string
          script: |
            const envJson = JSON.parse(process.env.SANDBOX_SECRETS);
            const sandbox = process.env.SANDBOX
            return envJson[sandbox]
      
      - name: 🖨️ Print Password
        run: echo "${{steps.set-password.outputs.result}}"

          
