name: READ VARIABLES

on:
  push:
    branches:
      - main

env:
  SANDBOX_SECRETS: ${{ secrets.SANDBOX_SECRETS }}

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner: ['stage', 'uat', 'qa']

    steps:
      - name: Setup Node
        id: setup-noe
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v4

      - name: Set Mapped Password
        env:
          SANDBOX: ${{ matrix.runner }}
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('PASSWORD', $(node .github/utils/index.js));
      
      - name: Print the password
        run: echo $PASSWORD

          
